name: srcker_utils
description: 常用工具类
version: 0.1.0
homepage: https://srcker.com

environment:
  sdk: '>=3.1.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# flutter:
#   plugin:
#     platforms:
#       android:
#         package: com.srcker.utils
#         pluginClass: SrckerFlutterUtilsPlugin
#       ios:
#         pluginClass: SrckerFlutterUtilsPlugin